# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 19
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/cache@v2
        with:
          path: build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 19
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
